"""Message compaction helpers for long Harbor episodes."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from .openrouter_common import ensure_dir


SUMMARY_SYSTEM_PROMPT = """You are compacting earlier task history for a coding agent.

Summarize only what is already known.
Focus on facts that will help continue the task efficiently:
- confirmed environment facts
- commands already tried and their outcomes
- files created or modified
- errors or blockers discovered
- what still needs to be done next

Return plain markdown only.
Keep it concise and action-oriented.
Do not include speculative ideas unless they were explicitly tested.
"""


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


COMPACTION_TRIGGER_INPUT_TOKENS = _env_int("KTB_COMPACTION_TRIGGER_INPUT_TOKENS", 12000)
COMPACTION_RECENT_MESSAGES = _env_int("KTB_COMPACTION_RECENT_MESSAGES", 8)
COMPACTION_SUMMARY_TOKENS = _env_int("KTB_COMPACTION_SUMMARY_TOKENS", 2000)
SUMMARY_MODEL = os.environ.get("OPENROUTER_SUMMARY_MODEL", "anthropic/claude-3.5-haiku")


def should_compact(last_input_tokens: int, messages: list[dict[str, Any]]) -> bool:
    return last_input_tokens >= COMPACTION_TRIGGER_INPUT_TOKENS and len(messages) > COMPACTION_RECENT_MESSAGES + 2


def is_prompt_too_long_error(exc: Exception) -> bool:
    message = str(exc).lower()
    markers = (
        "prompt is too long",
        "context length",
        "maximum context length",
        "too many input tokens",
        "context_length_exceeded",
    )
    return any(marker in message for marker in markers)


def _serialize_content(content: Any) -> Any:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        serialized: list[Any] = []
        for item in content:
            if isinstance(item, dict):
                serialized.append(item)
            else:
                serialized.append(str(item))
        return serialized
    return str(content)


def _extract_summary_text(response: Any) -> str:
    parts: list[str] = []
    for block in response.content:
        text = getattr(block, "text", None)
        if text:
            parts.append(text.strip())
    return "\n\n".join(part for part in parts if part).strip()


def compact_messages(
    *,
    client: Any,
    messages: list[dict[str, Any]],
    logs_dir: Path,
    compaction_index: int,
) -> list[dict[str, Any]]:
    recent_count = COMPACTION_RECENT_MESSAGES
    prefix_end = len(messages) - recent_count
    old_messages = messages[1:prefix_end]
    recent_messages = messages[prefix_end:]

    serialized_history = [
        {
            "role": message["role"],
            "content": _serialize_content(message["content"]),
        }
        for message in old_messages
    ]

    request_payload = {
        "task": messages[0]["content"],
        "history_to_compact": serialized_history,
    }
    response = client.messages.create(
        model=SUMMARY_MODEL,
        max_tokens=COMPACTION_SUMMARY_TOKENS,
        system=SUMMARY_SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": json.dumps(request_payload, indent=2, default=str),
            }
        ],
        temperature=0.0,
    )
    summary_text = _extract_summary_text(response)
    if not summary_text:
        summary_text = "No useful summary generated."

    compaction_dir = ensure_dir(logs_dir / "compactions")
    compaction_path = compaction_dir / f"compaction-{compaction_index:02d}.json"
    compaction_path.write_text(
        json.dumps(
            {
                "summary_model": SUMMARY_MODEL,
                "request": request_payload,
                "response": response.model_dump(mode="json"),
                "summary_text": summary_text,
            },
            indent=2,
            default=str,
        )
    )

    summary_message = {
        "role": "user",
        "content": (
            "Condensed summary of earlier work generated by the harness to save context:\n\n"
            f"{summary_text}"
        ),
    }
    return [messages[0], summary_message, *recent_messages]
